# .github/workflows/caller-workflow.yml
name: Token Update Caller

on:
  pull_request:
    types: [closed]

jobs:
  call-update-token:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/token-update-reusable.yml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
    secrets:
      UPDATE_SECRET: ${{ secrets.UPDATE_SECRET }}
